# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gunjan/opensoft

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gunjan/opensoft

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gunjan/opensoft/CMakeFiles /home/gunjan/opensoft/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gunjan/opensoft/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graph_separation

# Build rule for target.
graph_separation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph_separation
.PHONY : graph_separation

# fast build rule for target.
graph_separation/fast:
	$(MAKE) -f CMakeFiles/graph_separation.dir/build.make CMakeFiles/graph_separation.dir/build
.PHONY : graph_separation/fast

#=============================================================================
# Target rules for targets named graph_separation1

# Build rule for target.
graph_separation1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph_separation1
.PHONY : graph_separation1

# fast build rule for target.
graph_separation1/fast:
	$(MAKE) -f CMakeFiles/graph_separation1.dir/build.make CMakeFiles/graph_separation1.dir/build
.PHONY : graph_separation1/fast

graph_separation.o: graph_separation.cpp.o
.PHONY : graph_separation.o

# target to build an object file
graph_separation.cpp.o:
	$(MAKE) -f CMakeFiles/graph_separation.dir/build.make CMakeFiles/graph_separation.dir/graph_separation.cpp.o
.PHONY : graph_separation.cpp.o

graph_separation.i: graph_separation.cpp.i
.PHONY : graph_separation.i

# target to preprocess a source file
graph_separation.cpp.i:
	$(MAKE) -f CMakeFiles/graph_separation.dir/build.make CMakeFiles/graph_separation.dir/graph_separation.cpp.i
.PHONY : graph_separation.cpp.i

graph_separation.s: graph_separation.cpp.s
.PHONY : graph_separation.s

# target to generate assembly for a file
graph_separation.cpp.s:
	$(MAKE) -f CMakeFiles/graph_separation.dir/build.make CMakeFiles/graph_separation.dir/graph_separation.cpp.s
.PHONY : graph_separation.cpp.s

graph_separation1.o: graph_separation1.cpp.o
.PHONY : graph_separation1.o

# target to build an object file
graph_separation1.cpp.o:
	$(MAKE) -f CMakeFiles/graph_separation1.dir/build.make CMakeFiles/graph_separation1.dir/graph_separation1.cpp.o
.PHONY : graph_separation1.cpp.o

graph_separation1.i: graph_separation1.cpp.i
.PHONY : graph_separation1.i

# target to preprocess a source file
graph_separation1.cpp.i:
	$(MAKE) -f CMakeFiles/graph_separation1.dir/build.make CMakeFiles/graph_separation1.dir/graph_separation1.cpp.i
.PHONY : graph_separation1.cpp.i

graph_separation1.s: graph_separation1.cpp.s
.PHONY : graph_separation1.s

# target to generate assembly for a file
graph_separation1.cpp.s:
	$(MAKE) -f CMakeFiles/graph_separation1.dir/build.make CMakeFiles/graph_separation1.dir/graph_separation1.cpp.s
.PHONY : graph_separation1.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... graph_separation"
	@echo "... graph_separation1"
	@echo "... graph_separation.o"
	@echo "... graph_separation.i"
	@echo "... graph_separation.s"
	@echo "... graph_separation1.o"
	@echo "... graph_separation1.i"
	@echo "... graph_separation1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

